import { interestCategoriesSchema, userPreferencesSchema } from '@wanderly/contracts';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { mobileApiClient } from '../src/api-client';

export default function PreferencesScreen() {
  const [categories, setCategories] = useState<ReturnType<typeof interestCategoriesSchema.parse>>([]);
  const [selected, setSelected] = useState<string[]>([]); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { Promise.all([mobileApiClient.request('preferences/categories', { schema: interestCategoriesSchema }), mobileApiClient.request('preferences', { schema: userPreferencesSchema })]).then(([items, preferences]) => { setCategories(items); setSelected(preferences.categoryIds); }).catch((cause: unknown) => setMessage(cause instanceof Error ? cause.message : 'Không thể tải sở thích.')).finally(() => setLoading(false)); }, []);
  async function save() { if (selected.length < 3) { setMessage('Hãy chọn ít nhất 3 sở thích.'); return; } try { await mobileApiClient.request('preferences', { method: 'PUT', body: { categoryIds: selected }, schema: userPreferencesSchema }); setMessage('Đã lưu sở thích.'); } catch (cause) { setMessage(cause instanceof Error ? cause.message : 'Không thể lưu sở thích.'); } }
  if (loading) return <SafeAreaView style={styles.safe}><ActivityIndicator color="#277253" style={styles.loader} /></SafeAreaView>;
  return <SafeAreaView style={styles.safe}><View style={styles.container}><Text style={styles.title}>Sở thích của bạn</Text><Text style={styles.body}>Chọn tối thiểu 3 chủ đề.</Text><View style={styles.grid}>{categories.map((category) => <Pressable key={category.id} onPress={() => setSelected((current) => current.includes(category.id) ? current.filter((id) => id !== category.id) : [...current, category.id])} style={[styles.chip, selected.includes(category.id) && styles.active]}><Text style={styles.chipText}>{category.name}</Text></Pressable>)}</View><Pressable onPress={() => void save()} style={styles.button}><Text style={styles.buttonText}>Lưu sở thích</Text></Pressable>{!!message && <Text style={styles.message}>{message}</Text>}</View></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { backgroundColor: '#f4f7f2', flex: 1 }, loader: { flex: 1 }, container: { padding: 24 }, title: { color: '#17231f', fontSize: 34, fontWeight: '700' }, body: { color: '#52615b', marginTop: 12 }, grid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginTop: 24 }, chip: { backgroundColor: '#fff', borderColor: '#d8e1dc', borderRadius: 20, borderWidth: 1, paddingHorizontal: 16, paddingVertical: 11 }, active: { backgroundColor: '#dcece4', borderColor: '#277253' }, chipText: { color: '#18563d', fontWeight: '600' }, button: { backgroundColor: '#277253', borderRadius: 12, marginTop: 24, padding: 14 }, buttonText: { color: '#fff', fontWeight: '700', textAlign: 'center' }, message: { color: '#52615b', marginTop: 14 } });
