import { IndoorOutdoor } from '@prisma/client';

export const categorySeeds = [
  { slug: 'cafe', name: 'Cà phê', icon: 'coffee' },
  { slug: 'food', name: 'Ẩm thực', icon: 'utensils' },
  { slug: 'art', name: 'Nghệ thuật', icon: 'palette' },
  { slug: 'outdoor', name: 'Ngoài trời', icon: 'trees' },
  { slug: 'photography', name: 'Chụp ảnh', icon: 'camera' },
  { slug: 'culture', name: 'Văn hóa', icon: 'landmark' },
  { slug: 'shopping', name: 'Mua sắm', icon: 'shopping-bag' },
  { slug: 'entertainment', name: 'Giải trí', icon: 'sparkles' },
] as const;

type PlaceSeed = {
  slug: string;
  name: string;
  description: string;
  address: string;
  district: string;
  latitude: number;
  longitude: number;
  rating: number;
  reviewCount: number;
  priceMin: number;
  priceMax: number;
  durationMinutes: number;
  indoorOutdoor: IndoorOutdoor;
  popularityScore: number;
  categories: Array<{ slug: string; relevance: number }>;
  opening: { open: string; close: string };
};

export const placeSeeds: PlaceSeed[] = [
  {
    slug: 'wanderly-lakeside-coffee-lab',
    name: 'Wanderly Lakeside Coffee Lab',
    description:
      'Không gian cà phê demo có khu vực làm việc và góc nhìn ra hồ.',
    address: 'Khu demo Hồ Tây',
    district: 'Tây Hồ',
    latitude: 21.0587,
    longitude: 105.8194,
    rating: 4.7,
    reviewCount: 184,
    priceMin: 45000,
    priceMax: 120000,
    durationMinutes: 90,
    indoorOutdoor: IndoorOutdoor.MIXED,
    popularityScore: 0.91,
    categories: [
      { slug: 'cafe', relevance: 1 },
      { slug: 'photography', relevance: 0.65 },
    ],
    opening: { open: '07:00', close: '22:30' },
  },
  {
    slug: 'wanderly-old-quarter-kitchen',
    name: 'Wanderly Old Quarter Kitchen',
    description: 'Bếp Việt demo phục vụ món địa phương theo mùa.',
    address: 'Khu demo Phố Cổ',
    district: 'Hoàn Kiếm',
    latitude: 21.0332,
    longitude: 105.8501,
    rating: 4.6,
    reviewCount: 322,
    priceMin: 80000,
    priceMax: 250000,
    durationMinutes: 75,
    indoorOutdoor: IndoorOutdoor.INDOOR,
    popularityScore: 0.88,
    categories: [
      { slug: 'food', relevance: 1 },
      { slug: 'culture', relevance: 0.45 },
    ],
    opening: { open: '10:00', close: '22:00' },
  },
  {
    slug: 'wanderly-contemporary-art-space',
    name: 'Wanderly Contemporary Art Space',
    description: 'Không gian triển lãm demo dành cho nghệ thuật đương đại.',
    address: 'Khu demo Tràng Tiền',
    district: 'Hoàn Kiếm',
    latitude: 21.0244,
    longitude: 105.8551,
    rating: 4.8,
    reviewCount: 96,
    priceMin: 0,
    priceMax: 100000,
    durationMinutes: 120,
    indoorOutdoor: IndoorOutdoor.INDOOR,
    popularityScore: 0.78,
    categories: [
      { slug: 'art', relevance: 1 },
      { slug: 'culture', relevance: 0.8 },
      { slug: 'photography', relevance: 0.55 },
    ],
    opening: { open: '09:00', close: '18:00' },
  },
  {
    slug: 'wanderly-riverside-green-park',
    name: 'Wanderly Riverside Green Park',
    description: 'Công viên demo phù hợp đi bộ, picnic và ngắm hoàng hôn.',
    address: 'Khu demo ven sông Hồng',
    district: 'Long Biên',
    latitude: 21.0417,
    longitude: 105.8752,
    rating: 4.5,
    reviewCount: 210,
    priceMin: 0,
    priceMax: 0,
    durationMinutes: 120,
    indoorOutdoor: IndoorOutdoor.OUTDOOR,
    popularityScore: 0.83,
    categories: [
      { slug: 'outdoor', relevance: 1 },
      { slug: 'photography', relevance: 0.8 },
    ],
    opening: { open: '05:30', close: '21:00' },
  },
  {
    slug: 'wanderly-craft-market',
    name: 'Wanderly Craft Market',
    description: 'Chợ thủ công demo với đồ lưu niệm và workshop cuối tuần.',
    address: 'Khu demo Ba Đình',
    district: 'Ba Đình',
    latitude: 21.0359,
    longitude: 105.8292,
    rating: 4.4,
    reviewCount: 145,
    priceMin: 30000,
    priceMax: 500000,
    durationMinutes: 100,
    indoorOutdoor: IndoorOutdoor.MIXED,
    popularityScore: 0.74,
    categories: [
      { slug: 'shopping', relevance: 1 },
      { slug: 'culture', relevance: 0.7 },
      { slug: 'art', relevance: 0.5 },
    ],
    opening: { open: '09:00', close: '20:00' },
  },
  {
    slug: 'wanderly-rooftop-cinema',
    name: 'Wanderly Rooftop Cinema',
    description: 'Rạp phim ngoài trời demo với suất chiếu buổi tối.',
    address: 'Khu demo Đống Đa',
    district: 'Đống Đa',
    latitude: 21.0146,
    longitude: 105.8298,
    rating: 4.6,
    reviewCount: 118,
    priceMin: 120000,
    priceMax: 220000,
    durationMinutes: 150,
    indoorOutdoor: IndoorOutdoor.OUTDOOR,
    popularityScore: 0.8,
    categories: [
      { slug: 'entertainment', relevance: 1 },
      { slug: 'art', relevance: 0.35 },
    ],
    opening: { open: '17:00', close: '23:30' },
  },
  {
    slug: 'wanderly-family-fun-studio',
    name: 'Wanderly Family Fun Studio',
    description: 'Khu vui chơi trong nhà demo cho gia đình và nhóm bạn.',
    address: 'Khu demo Cầu Giấy',
    district: 'Cầu Giấy',
    latitude: 21.0313,
    longitude: 105.7907,
    rating: 4.3,
    reviewCount: 267,
    priceMin: 100000,
    priceMax: 300000,
    durationMinutes: 150,
    indoorOutdoor: IndoorOutdoor.INDOOR,
    popularityScore: 0.77,
    categories: [{ slug: 'entertainment', relevance: 1 }],
    opening: { open: '09:00', close: '21:30' },
  },
  {
    slug: 'wanderly-garden-brunch',
    name: 'Wanderly Garden Brunch',
    description: 'Nhà hàng brunch demo có sân vườn và thực đơn chay.',
    address: 'Khu demo Tây Hồ',
    district: 'Tây Hồ',
    latitude: 21.0671,
    longitude: 105.8238,
    rating: 4.7,
    reviewCount: 201,
    priceMin: 100000,
    priceMax: 320000,
    durationMinutes: 100,
    indoorOutdoor: IndoorOutdoor.MIXED,
    popularityScore: 0.86,
    categories: [
      { slug: 'food', relevance: 1 },
      { slug: 'cafe', relevance: 0.7 },
      { slug: 'photography', relevance: 0.45 },
    ],
    opening: { open: '07:30', close: '17:00' },
  },
  {
    slug: 'wanderly-heritage-workshop',
    name: 'Wanderly Heritage Workshop',
    description: 'Workshop demo giới thiệu kỹ thuật thủ công truyền thống.',
    address: 'Khu demo Hai Bà Trưng',
    district: 'Hai Bà Trưng',
    latitude: 21.0088,
    longitude: 105.8584,
    rating: 4.9,
    reviewCount: 72,
    priceMin: 150000,
    priceMax: 400000,
    durationMinutes: 120,
    indoorOutdoor: IndoorOutdoor.INDOOR,
    popularityScore: 0.72,
    categories: [
      { slug: 'culture', relevance: 1 },
      { slug: 'art', relevance: 0.85 },
    ],
    opening: { open: '09:00', close: '19:00' },
  },
  {
    slug: 'wanderly-night-food-court',
    name: 'Wanderly Night Food Court',
    description: 'Khu ẩm thực đêm demo với nhiều lựa chọn theo ngân sách.',
    address: 'Khu demo Thanh Xuân',
    district: 'Thanh Xuân',
    latitude: 20.9978,
    longitude: 105.8113,
    rating: 4.2,
    reviewCount: 410,
    priceMin: 30000,
    priceMax: 180000,
    durationMinutes: 90,
    indoorOutdoor: IndoorOutdoor.MIXED,
    popularityScore: 0.89,
    categories: [
      { slug: 'food', relevance: 1 },
      { slug: 'entertainment', relevance: 0.4 },
    ],
    opening: { open: '16:00', close: '23:45' },
  },
];
